"""empty message

Revision ID: 04e807f2b762
Revises: 91f187a8440a
Create Date: 2023-04-12 20:40:54.713119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e807f2b762'
down_revision = '91f187a8440a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
