"""empty message

Revision ID: 4d02bf64694d
Revises: 67595131b7b4
Create Date: 2023-04-12 20:46:20.483419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d02bf64694d'
down_revision = '67595131b7b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###
