"""empty message

Revision ID: 67595131b7b4
Revises: 04e807f2b762
Create Date: 2023-04-12 20:41:53.261349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67595131b7b4'
down_revision = '04e807f2b762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
